version: '3'
services:
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules # Use in container node_modules
            - .:/app            # Use build context volume for everything else
    # Container to run tests
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules # Use in container node_modules
            - .:/app            # Use build context volume for everything else
        command: ["npm", "run", "test"]
